OWNER_NAME="Nadun"
PREFIX="."
PUBLIC_MODE='yes'
AUTO_READ_STATUS="yes"
AUTO_DOWNLOAD_STATUS="no"
BOT_NAME= "𝘽𝙈𝙒-𝙈𝘿"
IMAGE_MENU= "https://telegra.ph/file/071f797dda6aef5ae3877.jpg"
NUMERO_OWNER= "+94760405102"
OWNER_NAME= "᚛Ibrahim Adams᚜"
DATABASE_URL= "mongodb+srv://Nadun:Nadun@679@nadun.ngodnom.mongodb.net"
WARN_COUNT= "3"
OPENAI_API_KEY= ""
STARTING_BOT_MESSAGE='yes'
ANTI_DELETE_MESSAGE='yes'
